### ISSUE TITLE
Friends frontend

### ISSUE THREAD

**Issue by tommyr418** [tommyr418/FacePlace#7]
util: friend_api_util, user_api_util: fetchRequests, fetchFriends
actions: friend_actions, user_actions: fetchRequests, fetchFriends
components: main-show>friends pane, header>friend requests dropdown, cover photo> add friend button

**Comment by m1010j** [comment]
- [ ] Your log-in button isn't working anymore.

- [ ] You should display an error on signup when the user tries to select a password that lies in the future.

- [ ] Instead of squeezing the wallpaper into its container, you should use `background-size: cover` and `background-position: center center`

**Comment by m1010j** [comment]
- [ ] Session errors look great, but the session page breaks if I try to sign up and leave a field blank.
